description: "Personal website of Aftab Sama"
google_analytics: G-T8K5YV4W6E
ga_analytics: G-T8K5YV4W6E

# Setup
title: Home
url: https://aftab700.github.io/Test
paginate: 1
#baseurl: "/Test"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-feed
  - jekyll-remote-theme

markdown: kramdown
# kramdown:
#   parse_block_html: true

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: Aftab Sama
  url: https://github.com/Aftab700/
  email: mrmr40873@gmail.com

# Custom vars
version: 0.0.1

# Navbar page list
nav:
  - title: About
    url: Random-Stoic-Quotes

